### ISSUE TITLE
createHeader: prealloc failed: operation not supported

### ISSUE THREAD

**Issue by jjellinek** [rfjakob/gocryptfs#25]
I am using Software RAID, LVM, and ext3 File system. gocryptfs works fine on my ubuntu 14.04 LTS install on regular partitions (non RAID/LVM) but when I try to mount my RAID/LVM partition and use this I get the above error whenever I try to create a file. I get a message in Vi about disk space not available (however there are GBs free)

**Comment by rfjakob** [comment]
Hi! What filesystem do you have on the raid?

**Comment by rfjakob** [comment]
My guess is ZFS. Please take a look at https://github.com/rfjakob/gocryptfs/issues/22 or just upgrade to latest master, gocryptfs now works on ZFS as well.

**Comment by jjellinek** [comment]
No, it's ext3! I will have another fiddle, I may be doing something silly with mountpoints etc.
I'm trying to mount a set of USB drives using software RAID5, with LVM and ext3. All that works, but then using gocryptfs gives me the error.

**Comment by rfjakob** [comment]
Oh, maybe ext3 does not support fallocate, either?
Anyway, the latest version will just warn once about that and continue
working.

**Comment by jjellinek** [comment]
Great, I will try that.

**Comment by jjellinek** [comment]
OK got it working with ext4 now and 0.9 binary. Couldn't get latest master to compile on Ubuntu 14.04 LTS as the golang is too old I think to have fuse libraries.

**Comment by rfjakob** [comment]
Oh, I see. Ubuntu 14.04 has Go 1.2 that lacks sync.Pool:
```
$ go version
go version go1.2.1 linux/amd64
$ go build
# github.com/hanwen/go-fuse/fuse
../../hanwen/go-fuse/fuse/server.go:44: undefined: sync.Pool
../../hanwen/go-fuse/fuse/server.go:47: undefined: sync.Pool
```

**Comment by rfjakob** [comment]
Released v0.10-rc3 that contains the fix. Binaries are available at https://github.com/rfjakob/gocryptfs/releases/tag/v0.10-rc3
