### ISSUE TITLE
MacOS failed to build on 2.1.1

### ISSUE THREAD

**Issue by litori** [rfjakob/gocryptfs#597]
Getting the following error while building gocryptfs 2.1.1 on M1 mac with Macfuse 4.1.2.  Worked fine on 2.1.

```gocryptfs % ./build-without-openssl.bash 
# github.com/hanwen/go-fuse/v2/fuse
../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20210825070001-74a933d6e856/fuse/server.go:122:5: undefined: parseFuseFd
../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.1.1-0.20210825070001-74a933d6e856/fuse/server.go:887:5: undefined: parseFuseFd
```

**Comment by rfjakob** [comment]
Yes, unfortunately I broke it with this commit https://github.com/hanwen/go-fuse/commit/74a933d6e856048cbff1a437bf3dbf79162e77de , but it's fixed now, thanks!
